spring:
  datasource:
    url: jdbc:mysql://localhost:3306/z_treeshop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: bes
    password: 1234
  redis:
    host: 127.0.0.1 #192.168.65.66 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

logging:
  level:
    root: info
    com.tulingxueyuan: debug

