spring:
  datasource:
    url: jdbc:mysql://localhost:3306/z_treeshop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: bes
    password: 1234
  redis:
    host: 127.0.0.1 #192.168.65.66 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

logging:
  level:
    root: info
    com.tulingxueyuan: debug

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com # oss对外服务的访问域名oss-cn-chengdu.aliyuncs.com
    accessKeyId:  # 访问身份验证中用到用户标识
    accessKeySecret:  # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: tjl-my-file # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    #callback:  # 文件上传成功后的回调地址
    dir:
      prefix: picture/ # 上传文件夹路径前缀
